name       : exiv2
version    : '0.26'
release    : 10
source     :
    - http://www.exiv2.org/builds/exiv2-0.26-trunk.tar.gz : c75e3c4a0811bf700d92c82319373b7a825a2331c12b8b37d41eb58e4f18eafb
license    : GPL-2.0-or-later
component  : desktop.library
summary    : exif and iptc metadata manipulation library and tools
description: |
    Exiv2, a C++ library and a command line utility to read and write Exif, IPTC and XMP image metadata.
builddeps  :
    - pkgconfig(libcurl)
    - pkgconfig(libssh)
setup      : |
    %apply_patches
    %configure --disable-static \
               --enable-video \
               --enable-webready \
               --with-curl \
               --with-ssh \
               --with-expat
build      : |
    %make
install    : |
    %make_install
