name        : exiv2
version     : 0.25
release     : 5
source     :
    - http://www.exiv2.org/exiv2-0.25.tar.gz : c80bfc778a15fdb06f71265db2c3d49d8493c382e516cb99b8c9f9cbde36efa4
license     : GPL-2.0+
summary     : exif and iptc metadata manipulation library and tools
description : |
    exif and iptc metadata manipulation library and tools
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
