name       : exiv2
version    : 0.27.2
release    : 12
source     :
    - https://exiv2.org/builds/exiv2-0.27.2-Source.tar.gz : 2652f56b912711327baff6dc0c90960818211cf7ab79bb5e1eb59320b78d153f
license    : GPL-2.0-or-later
component  : desktop.library
summary    : exif and iptc metadata manipulation library and tools
description: |
    Exiv2, a C++ library and a command line utility to read and write Exif, IPTC and XMP image metadata.
builddeps  :
    - pkgconfig(libcurl)
rundeps    :
    - devel :
        - curl-devel
setup      : |
    %patch -p1 < $pkgfiles/security/CVE-2019-13504.patch
    %cmake_ninja \
        -DEXIV2_ENABLE_CURL=on \
        -DEXIV2_ENABLE_DYNAMIC_RUNTIME=off \
        -DEXIV2_ENABLE_NLS=on \
        -DEXIV2_ENABLE_VIDEO=on \
        -DEXIV2_ENABLE_WEBREADY=on .
build      : |
    %ninja_build
install    : |
    %ninja_install
